### ISSUE TITLE
Replace `ls` with `exa`🦀

### ISSUE THREAD

**Issue by AjayShanker-geek** [ivaquero/oxidizer.sh#3]
Hi, I would like a share `ls` replacement as [exa](https://github.com/ogham/exa), the best part is that it is written is rust.

**Comment by ivaquero** [comment]
Hi, exa is a great rusty command line and I have observed its repo for quite a time. However, it doesn't support windows yet. 

This project aims to provide the same configuration and usage across macOS, Linux and Windows. So I choose lsd at the moment. When exa supports Windows, I will switch to exa certainly.

**Comment by AjayShanker-geek** [comment]
Ohh, I miss out that it doesn't support Windows. Cheers!
